DROP TABLE CONTACTS IF EXISTS;
DROP TABLE PHONES IF EXISTS;

CREATE TABLE CONTACTS (
ID INT PRIMARY KEY AUTO_INCREMENT,
FIRST_NAME VARCHAR(30),
LAST_NAME VARCHAR(30)
);

CREATE TABLE PHONES (
ID INT PRIMARY KEY AUTO_INCREMENT,
NUMBER VARCHAR(30),
TYPE TINYINT,
CONTACT_ID INT,
FOREIGN KEY (CONTACT_ID) REFERENCES CONTACTS(ID) ON DELETE CASCADE
);


INSERT INTO CONTACTS (FIRST_NAME, LAST_NAME)
VALUES ('Ivan', 'Ivanov');

INSERT INTO PHONES (NUMBER, TYPE, CONTACT_ID)
VALUES ('+7999111222', 0, 1);