DROP TABLE PRODUCTS IF EXISTS;
DROP TABLE ORDERS IF EXISTS;

CREATE TABLE PRODUCTS (
ID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(30),
PRICE INT,
COMMENTS VARCHAR(30)
);

CREATE TABLE ORDERS (
ID INT PRIMARY KEY AUTO_INCREMENT,
CUSTOMERNAME VARCHAR(30),
CUSTOMERPHONE VARCHAR (30),
CUSTOMERORDER VARCHAR (30),
);
INSERT INTO PRODUCTS (NAME,PRICE,COMMENTS)
VALUES ('Ivan', 'Ivanov');